name: Build PubMed RSS

on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Build RSS feed
        run: python main.py
      - name: Commit and push feed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs/feed.xml
          git commit -m "Update RSS feed [auto]"
          git push https://Chintal9:${GH_TOKEN}@github.com/Chintal9/Stroke-Journals-.git HEAD:main